version: '3'
services:
  app:
    build: .
    volumes:
      - ../laravel:/var/www/html/workspace
    ports:
      - 8000:8000
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
